#!/bin/bash
# именно так компилируют программы на курсе
g++ -Werror=vla -O2 -Wall -Werror -std=c++20 -lm -DSEBELEV_MAKSIM_MAKSIMOVICH=1 "$1".cpp -o build/"$1" || exit 1
echo "Nice build, bro"
echo

if [ $# -eq 2 ];
then
    build/"$1" < tests/"$2"
else
    build/"$1"
fi
